[tools]
bun = "latest"
clojure = "latest"
lein = "latest"
node = "lts"
pnpm = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
python.uv_venv_auto = true

[plugins]
lein = "https://codeberg.org/malice/asdf-lein.git"
